### ISSUE TITLE
App dies with cloud dev config

### ISSUE THREAD

**Issue by fogfish** [zalando/znap#37]
```
ZNAP_CONFIG_FILE=s3://xxx/znap-cs-dev/znap.conf
```

https://github.com/zalando/znap/blob/master/src/main/scala/org/zalando/znap/config/Config.scala#L106

```
Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'id'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:246)
	at org.zalando.znap.config.Config$.org$zalando$znap$config$Config$$readSnapshotTarget(Config.scala:107)
```

**Comment by ivanyu** [comment]
@fogfish should work now
